### PR TITLE
Fix #4 Proposal: Parse rotations as Linear.Quaternion

### LINKED ISSUE #4: Proposal: Parse rotations as `Linear.Quaternion`
Parsing rotations as `Linear.Quaternions` would make more of the functionality of `Linear` available, such as `fromQuaternion` and `mkTransformation` from `Linear.Matrix`. It would also abstract away the convention GlTF uses to represent a Quaternion as a 4-vector to something with more structure, while still having a public facing constructor for people who need lower level access.

### PR DESCRIPTION
**Pull request by mrehayden1**

### CODE REVIEW

**Comment by sgillespie** [comment]
I'm getting a build failure here too: https://github.com/sgillespie/haskell-gltf-loader/actions/runs/7993208043/job/21875482062?pr=8

**Comment by mrehayden1** [comment]
Will have a look into this shortly.

**Comment by mrehayden1** [comment]
Tests should be fixed now.

**Review by sgillespie — APPROVED** [review]
Well done, thanks!

**Pull request merged**
