### PR TITLE
Decode matrices in column-major order.

### LINKED ISSUE #16: Matrices are deocded in row-major order.
As per the spec, quoted below.

> 3.6.2.4. Data Alignment
>
>[...]
>
>Accessors of matrix type have data stored in column-major order;

However, the `getMat2`, `getMat3` and `getMat4` decoders read matrix components into the default order of `Linear.Matrix` matrices, which are all stored in row order.

### PR DESCRIPTION
**Pull request by mrehayden1**
Fixes #16.

I suppose these will be tested indirectly when I've finished the work on animations, which is the reason why I discovered this one!

### CODE REVIEW

**Comment by mrehayden1** [comment]
I think I might try and disable these hlint warnings since the alternative it suggests is more unreadable while being more idiomatic Haskell.

**Comment by sgillespie** [comment]
> I think I might try and disable these hlint warnings since the alternative it suggests is more unreadable while being more idiomatic Haskell.

Yes, please do!

**Comment by mrehayden1** [comment]
I've just learned how to do it so I'll try and push the build fixes shortly

**Comment by mrehayden1** [comment]
Oh and please would you double check the matrix definitions? I've already caught myself messing them up twice!

**Comment by sgillespie** [comment]
> Oh and please would you double check the matrix definitions? I've already caught myself messing them up twice!

Matrix definitions LGTM!

**Comment by mrehayden1** [comment]
I've added a pragma to supress the hlint warnings, but I might need your help to replicate the build failures.

**Pull request merged**
